<?php

namespace Database\Seeders;

use App\Models\SocialCase\BeneficiaryIntake;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class SampleStep1TodayIntakeSeeder extends Seeder
{
    /**
     * Run the database seeds for Step 1 Today's Intake module testing.
     */
    public function run(): void
    {
        $today = Carbon::today()->toDateString();

        $encoder = User::where('id', 5)->first()
            ?? User::where('role', 'admin')->first()
            ?? User::first();

        $encoderId = $encoder?->id;

        $beneficiaries = [
            [
                'control_number' => 'MSWDO-2026-00020',
                'beneficiary_first_name' => 'Mateo',
                'beneficiary_middle_name' => 'Cruz',
                'beneficiary_last_name' => 'Mendoza',
                'beneficiary_street_address' => 'Purok 2',
                'beneficiary_barangay' => 'Biga I',
                'beneficiary_contact_number' => '09171110020',
                'beneficiary_birthday' => '1985-03-15',
                'beneficiary_sex' => 'Male',
                'beneficiary_civil_status' => 'Married',
                'beneficiary_category' => 'Indigent Resident',
                'beneficiary_categories' => ['Indigent Resident'],
                'assistance_purpose' => 'Hospital Bill / Medical Needs',
            ],
            [
                'control_number' => 'MSWDO-2026-00021',
                'beneficiary_first_name' => 'Teresa',
                'beneficiary_middle_name' => 'Santos',
                'beneficiary_last_name' => 'Ramos',
                'beneficiary_street_address' => 'Tibayan Compound',
                'beneficiary_barangay' => 'Biga II',
                'beneficiary_contact_number' => '09171110021',
                'beneficiary_birthday' => '1992-07-22',
                'beneficiary_sex' => 'Female',
                'beneficiary_civil_status' => 'Single',
                'beneficiary_category' => 'Solo Parents',
                'beneficiary_categories' => ['Solo Parents'],
                'assistance_purpose' => 'Hospital Bill / Medical Needs',
            ],
            [
                'control_number' => 'MSWDO-2026-00022',
                'beneficiary_first_name' => 'Danilo',
                'beneficiary_middle_name' => 'Reyes',
                'beneficiary_last_name' => 'Villanueva',
                'beneficiary_street_address' => 'Purok 1',
                'beneficiary_barangay' => 'Balite I',
                'beneficiary_contact_number' => '09171110022',
                'beneficiary_birthday' => '1960-11-08',
                'beneficiary_sex' => 'Male',
                'beneficiary_civil_status' => 'Married',
                'beneficiary_category' => 'Senior Citizen',
                'beneficiary_categories' => ['Senior Citizen'],
                'assistance_purpose' => 'Cardiovascular',
            ],
            [
                'control_number' => 'MSWDO-2026-00023',
                'beneficiary_first_name' => 'Maria Elena',
                'beneficiary_middle_name' => 'Bautista',
                'beneficiary_last_name' => 'Garcia',
                'beneficiary_street_address' => 'Block 3 Lot 5',
                'beneficiary_barangay' => 'Balite II',
                'beneficiary_contact_number' => '09171110023',
                'beneficiary_birthday' => '1978-05-19',
                'beneficiary_sex' => 'Female',
                'beneficiary_civil_status' => 'Married',
                'beneficiary_category' => 'Indigent Resident',
                'beneficiary_categories' => ['Indigent Resident'],
                'assistance_purpose' => 'Diabetes',
            ],
            [
                'control_number' => 'MSWDO-2026-00024',
                'beneficiary_first_name' => 'Ricardo',
                'beneficiary_middle_name' => 'Gonzales',
                'beneficiary_last_name' => 'Fernandez',
                'beneficiary_street_address' => 'Purok 4',
                'beneficiary_barangay' => 'Kaong',
                'beneficiary_contact_number' => '09171110024',
                'beneficiary_birthday' => '1995-09-30',
                'beneficiary_sex' => 'Male',
                'beneficiary_civil_status' => 'Single',
                'beneficiary_category' => 'PWD',
                'beneficiary_categories' => ['PWD'],
                'assistance_purpose' => 'Trauma and Injury',
            ],
            [
                'control_number' => 'MSWDO-2026-00025',
                'beneficiary_first_name' => 'Corazon',
                'beneficiary_middle_name' => 'Diaz',
                'beneficiary_last_name' => 'Aquino',
                'beneficiary_street_address' => 'Sitio Ilaya',
                'beneficiary_barangay' => 'Tibig',
                'beneficiary_contact_number' => '09171110025',
                'beneficiary_birthday' => '1958-02-14',
                'beneficiary_sex' => 'Female',
                'beneficiary_civil_status' => 'Widowed',
                'beneficiary_category' => 'Senior Citizen',
                'beneficiary_categories' => ['Senior Citizen'],
                'assistance_purpose' => 'Kidney Diseases',
            ],
            [
                'control_number' => 'MSWDO-2026-00026',
                'beneficiary_first_name' => 'Rolando',
                'beneficiary_middle_name' => 'Castillo',
                'beneficiary_last_name' => 'Navarro',
                'beneficiary_street_address' => 'Purok 3',
                'beneficiary_barangay' => 'Tartaria',
                'beneficiary_contact_number' => '09171110026',
                'beneficiary_birthday' => '1981-12-03',
                'beneficiary_sex' => 'Male',
                'beneficiary_civil_status' => 'Married',
                'beneficiary_category' => 'Indigent Resident',
                'beneficiary_categories' => ['Indigent Resident'],
                'assistance_purpose' => 'Hospital Bill / Medical Needs',
            ],
            [
                'control_number' => 'MSWDO-2026-00027',
                'beneficiary_first_name' => 'Jovita',
                'beneficiary_middle_name' => 'Perez',
                'beneficiary_last_name' => 'Mercado',
                'beneficiary_street_address' => 'Purok 2',
                'beneficiary_barangay' => 'Sabutan',
                'beneficiary_contact_number' => '09171110027',
                'beneficiary_birthday' => '1989-08-25',
                'beneficiary_sex' => 'Female',
                'beneficiary_civil_status' => 'Single',
                'beneficiary_category' => 'Solo Parents',
                'beneficiary_categories' => ['Solo Parents'],
                'assistance_purpose' => 'Surgical',
            ],
            [
                'control_number' => 'MSWDO-2026-00028',
                'beneficiary_first_name' => 'Nestor',
                'beneficiary_middle_name' => 'Delos Santos',
                'beneficiary_last_name' => 'Castro',
                'beneficiary_street_address' => 'Sitio Puting Tubig',
                'beneficiary_barangay' => 'Malabag',
                'beneficiary_contact_number' => '09171110028',
                'beneficiary_birthday' => '1974-04-10',
                'beneficiary_sex' => 'Male',
                'beneficiary_civil_status' => 'Married',
                'beneficiary_category' => 'Indigent Resident',
                'beneficiary_categories' => ['Indigent Resident'],
                'assistance_purpose' => 'Respiratory Diseases',
            ],
            [
                'control_number' => 'MSWDO-2026-00029',
                'beneficiary_first_name' => 'Carmelita',
                'beneficiary_middle_name' => 'Soriano',
                'beneficiary_last_name' => 'Tolentino',
                'beneficiary_street_address' => 'National Highway',
                'beneficiary_barangay' => 'Lalaan I',
                'beneficiary_contact_number' => '09171110029',
                'beneficiary_birthday' => '1963-06-18',
                'beneficiary_sex' => 'Female',
                'beneficiary_civil_status' => 'Widowed',
                'beneficiary_category' => 'Senior Citizen',
                'beneficiary_categories' => ['Senior Citizen'],
                'assistance_purpose' => 'Cardiovascular',
            ],
            [
                'control_number' => 'MSWDO-2026-00030',
                'beneficiary_first_name' => 'Arnel',
                'beneficiary_middle_name' => 'Macaraig',
                'beneficiary_last_name' => 'Valencia',
                'beneficiary_street_address' => 'Purok 1',
                'beneficiary_barangay' => 'Lalaan II',
                'beneficiary_contact_number' => '09171110030',
                'beneficiary_birthday' => '1998-01-27',
                'beneficiary_sex' => 'Male',
                'beneficiary_civil_status' => 'Single',
                'beneficiary_category' => 'Indigent Resident',
                'beneficiary_categories' => ['Indigent Resident'],
                'assistance_purpose' => 'Trauma and Injury',
            ],
            [
                'control_number' => 'MSWDO-2026-00031',
                'beneficiary_first_name' => 'Rowena',
                'beneficiary_middle_name' => 'Dimaculangan',
                'beneficiary_last_name' => 'Javier',
                'beneficiary_street_address' => 'Purok 5',
                'beneficiary_barangay' => 'Lucsuhin',
                'beneficiary_contact_number' => '09171110031',
                'beneficiary_birthday' => '1983-10-12',
                'beneficiary_sex' => 'Female',
                'beneficiary_civil_status' => 'Married',
                'beneficiary_category' => 'Solo Parents',
                'beneficiary_categories' => ['Solo Parents'],
                'assistance_purpose' => 'Hospital Bill / Medical Needs',
            ],
            [
                'control_number' => 'MSWDO-2026-00032',
                'beneficiary_first_name' => 'Edgardo',
                'beneficiary_middle_name' => 'Magpantay',
                'beneficiary_last_name' => 'Salazar',
                'beneficiary_street_address' => 'Sitio Gulod',
                'beneficiary_barangay' => 'Lumil',
                'beneficiary_contact_number' => '09171110032',
                'beneficiary_birthday' => '1970-03-05',
                'beneficiary_sex' => 'Male',
                'beneficiary_civil_status' => 'Married',
                'beneficiary_category' => 'Indigent Resident',
                'beneficiary_categories' => ['Indigent Resident'],
                'assistance_purpose' => 'Kidney Diseases',
            ],
            [
                'control_number' => 'MSWDO-2026-00033',
                'beneficiary_first_name' => 'Marites',
                'beneficiary_middle_name' => 'Manalo',
                'beneficiary_last_name' => 'De Castro',
                'beneficiary_street_address' => 'Purok 2',
                'beneficiary_barangay' => 'Pooc I',
                'beneficiary_contact_number' => '09171110033',
                'beneficiary_birthday' => '1990-11-16',
                'beneficiary_sex' => 'Female',
                'beneficiary_civil_status' => 'Married',
                'beneficiary_category' => 'Indigent Resident',
                'beneficiary_categories' => ['Indigent Resident'],
                'assistance_purpose' => 'Hospital Bill / Medical Needs',
            ],
            [
                'control_number' => 'MSWDO-2026-00034',
                'beneficiary_first_name' => 'Jaime',
                'beneficiary_middle_name' => 'Ilagan',
                'beneficiary_last_name' => 'Alcantara',
                'beneficiary_street_address' => 'Purok 4',
                'beneficiary_barangay' => 'Pooc II',
                'beneficiary_contact_number' => '09171110034',
                'beneficiary_birthday' => '1976-07-08',
                'beneficiary_sex' => 'Male',
                'beneficiary_civil_status' => 'Married',
                'beneficiary_category' => 'PWD',
                'beneficiary_categories' => ['PWD'],
                'assistance_purpose' => 'Neurological Disorders',
            ],
            [
                'control_number' => 'MSWDO-2026-00035',
                'beneficiary_first_name' => 'Remedios',
                'beneficiary_middle_name' => 'Catacutan',
                'beneficiary_last_name' => 'Ocampo',
                'beneficiary_street_address' => 'Purok 3',
                'beneficiary_barangay' => 'Puting Kahoy',
                'beneficiary_contact_number' => '09171110035',
                'beneficiary_birthday' => '1955-09-21',
                'beneficiary_sex' => 'Female',
                'beneficiary_civil_status' => 'Widowed',
                'beneficiary_category' => 'Senior Citizen',
                'beneficiary_categories' => ['Senior Citizen'],
                'assistance_purpose' => 'Cardiovascular',
            ],
            [
                'control_number' => 'MSWDO-2026-00036',
                'beneficiary_first_name' => 'Gerry',
                'beneficiary_middle_name' => 'Panganiban',
                'beneficiary_last_name' => 'Rosales',
                'beneficiary_street_address' => 'Block 12 Lot 8',
                'beneficiary_barangay' => 'San Miguel I',
                'beneficiary_contact_number' => '09171110036',
                'beneficiary_birthday' => '1987-04-02',
                'beneficiary_sex' => 'Male',
                'beneficiary_civil_status' => 'Married',
                'beneficiary_category' => 'Indigent Resident',
                'beneficiary_categories' => ['Indigent Resident'],
                'assistance_purpose' => 'Diabetes',
            ],
            [
                'control_number' => 'MSWDO-2026-00037',
                'beneficiary_first_name' => 'Lilibeth',
                'beneficiary_middle_name' => 'Evangelista',
                'beneficiary_last_name' => 'Domingo',
                'beneficiary_street_address' => 'Purok 1',
                'beneficiary_barangay' => 'San Miguel II',
                'beneficiary_contact_number' => '09171110037',
                'beneficiary_birthday' => '1994-12-29',
                'beneficiary_sex' => 'Female',
                'beneficiary_civil_status' => 'Single',
                'beneficiary_category' => 'Solo Parents',
                'beneficiary_categories' => ['Solo Parents'],
                'assistance_purpose' => 'Surgical',
            ],
            [
                'control_number' => 'MSWDO-2026-00038',
                'beneficiary_first_name' => 'Fernando',
                'beneficiary_middle_name' => 'Beltran',
                'beneficiary_last_name' => 'Pascual',
                'beneficiary_street_address' => 'Purok 2',
                'beneficiary_barangay' => 'San Vicente I',
                'beneficiary_contact_number' => '09171110038',
                'beneficiary_birthday' => '1980-08-11',
                'beneficiary_sex' => 'Male',
                'beneficiary_civil_status' => 'Married',
                'beneficiary_category' => 'Indigent Resident',
                'beneficiary_categories' => ['Indigent Resident'],
                'assistance_purpose' => 'Hospital Bill / Medical Needs',
            ],
            [
                'control_number' => 'MSWDO-2026-00039',
                'beneficiary_first_name' => 'Rosalinda',
                'beneficiary_middle_name' => 'Austria',
                'beneficiary_last_name' => 'Guinto',
                'beneficiary_street_address' => 'Purok 3',
                'beneficiary_barangay' => 'San Vicente II',
                'beneficiary_contact_number' => '09171110039',
                'beneficiary_birthday' => '1968-05-24',
                'beneficiary_sex' => 'Female',
                'beneficiary_civil_status' => 'Married',
                'beneficiary_category' => 'Indigent Resident',
                'beneficiary_categories' => ['Indigent Resident'],
                'assistance_purpose' => 'Cancer',
            ],
            [
                'control_number' => 'MSWDO-2026-00040',
                'beneficiary_first_name' => 'Benjamin',
                'beneficiary_middle_name' => 'Cordero',
                'beneficiary_last_name' => 'De Leon',
                'beneficiary_street_address' => 'Purok 1',
                'beneficiary_barangay' => 'Pulong Bunga',
                'beneficiary_contact_number' => '09171110040',
                'beneficiary_birthday' => '1972-10-09',
                'beneficiary_sex' => 'Male',
                'beneficiary_civil_status' => 'Married',
                'beneficiary_category' => 'Indigent Resident',
                'beneficiary_categories' => ['Indigent Resident'],
                'assistance_purpose' => 'Cardiovascular',
            ],
            [
                'control_number' => 'MSWDO-2026-00041',
                'beneficiary_first_name' => 'Gina',
                'beneficiary_middle_name' => 'Malabanan',
                'beneficiary_last_name' => 'Dizon',
                'beneficiary_street_address' => 'Purok 2',
                'beneficiary_barangay' => 'Pulong Saging',
                'beneficiary_contact_number' => '09171110041',
                'beneficiary_birthday' => '1996-03-18',
                'beneficiary_sex' => 'Female',
                'beneficiary_civil_status' => 'Single',
                'beneficiary_category' => 'Solo Parents',
                'beneficiary_categories' => ['Solo Parents'],
                'assistance_purpose' => 'Hospital Bill / Medical Needs',
            ],
        ];

        foreach ($beneficiaries as $ben) {
            BeneficiaryIntake::updateOrCreate(
                ['control_number' => $ben['control_number']],
                [
                    'client_type' => 'New',
                    'date_processed' => $today,
                    'encoder' => $encoderId,
                    'is_client_beneficiary' => false,
                    'beneficiary_first_name' => $ben['beneficiary_first_name'],
                    'beneficiary_middle_name' => $ben['beneficiary_middle_name'],
                    'beneficiary_last_name' => $ben['beneficiary_last_name'],
                    'beneficiary_extension_name' => null,
                    'beneficiary_street_address' => $ben['beneficiary_street_address'],
                    'beneficiary_barangay' => $ben['beneficiary_barangay'],
                    'beneficiary_city' => 'Silang',
                    'beneficiary_province' => 'Cavite',
                    'beneficiary_region' => 'Region IV-A',
                    'beneficiary_contact_number' => $ben['beneficiary_contact_number'],
                    'beneficiary_birthday' => $ben['beneficiary_birthday'],
                    'beneficiary_age' => Carbon::parse($ben['beneficiary_birthday'])->age,
                    'beneficiary_sex' => $ben['beneficiary_sex'],
                    'beneficiary_civil_status' => $ben['beneficiary_civil_status'],
                    'beneficiary_category' => $ben['beneficiary_category'],
                    'beneficiary_categories' => $ben['beneficiary_categories'],
                    'assistance_purpose' => $ben['assistance_purpose'],
                    'service_provided' => 'Financial Assistance Intake',
                    'purpose' => 'Medical Assistance',
                    'submitted_to' => 'MSWDO Silang Main Office',
                    'interviewed_by' => 'FA Staff Step1',
                    'has_representative' => false,
                    'rep_first_name' => null,
                    'rep_middle_name' => null,
                    'rep_last_name' => null,
                    'rep_extension_name' => null,
                    'rep_street_address' => null,
                    'rep_barangay' => null,
                    'rep_city' => null,
                    'rep_province' => null,
                    'rep_region' => null,
                    'rep_contact_number' => null,
                    'rep_birthday' => null,
                    'rep_age' => null,
                    'rep_sex' => null,
                    'rep_civil_status' => null,
                    'rep_occupation' => null,
                    'rep_monthly_salary' => null,
                    'rep_relationship' => null,
                    'is_payroll_generated' => false,
                    'claim_status' => 'Unclaimed',
                    'is_archived' => false,
                ]
            );
        }
    }
}
