<!doctype html>
<html lang="en"><head><meta charset="utf-8"><style>
@page { margin: 28px 38px; } body { font-family: DejaVu Sans, sans-serif; font-size: 10px; color: #111; } .center{text-align:center}.header h1{font-size:15px;margin:3px 0}.header p{margin:2px 0}.rule{border-top:2px solid #111;margin:12px 0}.section{font-size:11px;font-weight:bold;margin:16px 0 6px}.grid{width:100%;border-collapse:collapse}.grid td,.grid th{border:1px solid #222;padding:5px;vertical-align:top}.grid th{background:#eee}.label{font-weight:bold;width:22%}.text{white-space:pre-line;line-height:1.45}.signatures{width:100%;margin-top:48px;text-align:center}.signatures td{width:50%;padding:20px}.line{border-top:1px solid #111;margin:24px auto 4px;width:80%}
</style></head><body>
<div class="header center"><p>Republic of the Philippines</p><p><strong>MUNICIPALITY OF SILANG</strong></p><p>Municipal Social Welfare and Development Office</p><div class="rule"></div><h1>SOCIAL CASE STUDY REPORT</h1></div>
@php($snapshot = $report->snapshot ?? [])
<table class="grid"><tr><td class="label">Case Number</td><td>{{ $report->case_number }}</td><td class="label">Date Processed</td><td>{{ data_get($snapshot, 'case.date_processed', '') }}</td></tr><tr><td class="label">Client</td><td colspan="3">{{ collect($snapshot['client'] ?? [])->filter()->implode(' ') }}</td></tr><tr><td class="label">Beneficiary</td><td colspan="3">{{ collect($snapshot['beneficiary'] ?? [])->only(['beneficiary_first_name','beneficiary_middle_name','beneficiary_last_name'])->filter()->implode(' ') }}</td></tr><tr><td class="label">Purpose</td><td colspan="3">{{ data_get($snapshot, 'case.purpose', '') }}</td></tr></table>
<div class="section">I. FAMILY COMPOSITION</div><table class="grid"><thead><tr><th>Name</th><th>Relationship</th><th>Age</th><th>Sex</th><th>Occupation</th><th>Monthly Income</th></tr></thead><tbody>@forelse($snapshot['family'] ?? [] as $member)<tr><td>{{ $member['full_name'] ?? '' }}</td><td>{{ $member['relationship'] ?? '' }}</td><td>{{ $member['age'] ?? '' }}</td><td>{{ $member['sex'] ?? '' }}</td><td>{{ $member['occupation'] ?? '' }}</td><td>{{ $member['monthly_income'] ?? '' }}</td></tr>@empty<tr><td colspan="6" class="center">No family members recorded.</td></tr>@endforelse</tbody></table>
<div class="section">II. PRESENTING PROBLEM / INTERVIEW</div><div class="text">{{ data_get($snapshot, 'interview.interview_reason', '') }}
{{ data_get($snapshot, 'interview.interview_situation', '') }}</div>
<div class="section">III. SOCIAL WORKER'S ASSESSMENT</div><div class="text">{{ data_get($snapshot, 'assessment.social_worker_assessment', '') }}</div>
<div class="section">IV. RECOMMENDATION</div><p>{{ data_get($snapshot, 'assessment.recommendation', '') }} @if(data_get($snapshot, 'assessment.recommended_amount')) — Recommended amount: PHP {{ number_format((float) data_get($snapshot, 'assessment.recommended_amount'), 2) }} @endif</p>
<table class="signatures"><tr><td><div class="line"></div>Prepared by<br>Social Case Study Officer</td></tr></table>
</body></html>
